# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

# Whenever there is a pull request (PR) or push to the "main" branch, the jobs specified below will run.
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Here, we specify the automatic cloud based testing that will be ran on pushes/PRs to "main"
jobs:
  wheels-windows_py39:
    runs-on: windows-latest
    # runs-on: ${{matrix.os}}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade numpy scipy setuptools wheel cython==0.29.28

      - name: Build wheels
        run: |
          # python setup.py build
          # python setup.py install --user
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          # archives:1
          name: dist
          path: dist
